
name: appium

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name : pull the project to runner
      uses: actions/checkout@v3 
    - name : set up appium
    
      run: |
            npm install -g appium@v1.22
            appium -v
            appium &>/dev/null &   
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v2
      with :
        api-level: 29
        script: mvn clean test -Pandroid 
        
